### ISSUE TITLE
 Looks like there is a lack of resources

### ISSUE THREAD

**Issue by Vivisky** [PedroHenriques/go-minesweeper#3]
when i run 
`go run main.go
`
error
```
# github.com/pedrohenriques/go-minesweeper/internal/gui
internal\gui\game.go:170:46: undefined: resourceMinePng
internal\gui\game.go:175:46: undefined: resourceLivesPng
internal\gui\game.go:180:42: undefined: resourceTimerPng
internal\gui\gui.go:26:14: undefined: resourceFaviconPng
internal\gui\tile.go:48:15: undefined: resourceIncorrectFlagPng
internal\gui\tile.go:51:14: undefined: resourceMinePng
internal\gui\tile.go:60:13: undefined: resourceFlagPng
```

**Comment by PedroHenriques** [comment]
Hello,

The repo had a shell script that would handle bundling the assets and then running the application, as was described in the readme file.

If you pull the new version of the main branch it will now have the bundled assets included and "go run ./main.go" will work.

**Comment by Vivisky** [comment]
Ok,thanks,it's worked.
At first I misunderstood the readme file.
